<?php

namespace AppBundle\Repository;


/**
 * ArticleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleRepository extends \Doctrine\ORM\EntityRepository
{

    public function getSearchTitle()
    {
        
            return $this->getEntityManager()
            ->createQuery(
                'SELECT a FROM AppBundle\Entity\Article AS a 
                WHERE a.title LIKE :p'
            );

    }

}
